-- SELECT ALL MOVIES

SELECT MOVIE.OBJECT_ID ID, MOVIE.NAME NAME, DESC_ATT.VALUE DESCRIPTION, DUR_ATT.VALUE DURATION, IMDB_ATT.VALUE IMDB,
PERIOD_ATT.VALUE PERIODICITY, BASE_ATT.VALUE BASE_PRICE, RSTART_ATT.DATE_VALUE, REND_ATT.DATE_VALUE, POSTER_ATT.VALUE
FROM OBJECTS MOVIE
INNER JOIN ATTRIBUTES DESC_ATT
ON MOVIE.OBJECT_ID = DESC_ATT.OBJECT_ID
INNER JOIN ATTRIBUTES DUR_ATT
ON MOVIE.OBJECT_ID = DUR_ATT.OBJECT_ID
INNER JOIN ATTRIBUTES IMDB_ATT
ON MOVIE.OBJECT_ID = IMDB_ATT.OBJECT_ID
INNER JOIN ATTRIBUTES PERIOD_ATT
ON MOVIE.OBJECT_ID = PERIOD_ATT.OBJECT_ID
INNER JOIN ATTRIBUTES BASE_ATT
ON MOVIE.OBJECT_ID = BASE_ATT.OBJECT_ID
INNER JOIN ATTRIBUTES RSTART_ATT
ON MOVIE.OBJECT_ID = RSTART_ATT.OBJECT_ID
INNER JOIN ATTRIBUTES REND_ATT
ON MOVIE.OBJECT_ID = REND_ATT.OBJECT_ID
INNER JOIN ATTRIBUTES POSTER_ATT
ON MOVIE.OBJECT_ID = POSTER_ATT.OBJECT_ID
WHERE
MOVIE.OBJECT_TYPE_ID = 1
AND
DESC_ATT.ATTR_ID = 1
AND
DUR_ATT.ATTR_ID = 2
AND
IMDB_ATT.ATTR_ID = 3
AND
PERIOD_ATT.ATTR_ID = 4
AND
BASE_ATT.ATTR_ID = 5
AND
RSTART_ATT.ATTR_ID = 6
AND
REND_ATT.ATTR_ID = 7
AND
POSTER_ATT.ATTR_ID = 8;

-- SELECT ALL HALLS

SELECT HALL.OBJECT_ID ID, HALL.NAME FROM OBJECTS HALL
WHERE
HALL.OBJECT_TYPE_ID = 2;

-- SELECT ZONE AND PLACES

SELECT ZONE.OBJECT_ID, ZONE.NAME ZNAME, PLACE.OBJECT_ID, PLACE.NAME PNAME
FROM OBJECTS ZONE, OBJECTS PLACE, OBJREFERENCE ZONE_PLACE_REF
WHERE
ZONE.OBJECT_TYPE_ID = 3
AND
PLACE.OBJECT_TYPE_ID = 4
AND
ZONE_PLACE_REF.REFERENCE = PLACE.OBJECT_ID -- MANY
AND
ZONE_PLACE_REF.OBJECT_ID = ZONE.OBJECT_ID; -- ONE
