DROP TABLE OBJTYPE CASCADE CONSTRAINTS;
DROP TABLE ATTRTYPE CASCADE CONSTRAINTS;
DROP TABLE OBJECTS CASCADE CONSTRAINTS;
DROP TABLE ATTRIBUTES CASCADE CONSTRAINTS;
DROP TABLE OBJREFERENCE CASCADE CONSTRAINTS;
DROP SEQUENCE get_obj_id;

CREATE SEQUENCE get_obj_id START WITH 9 MAXVALUE 999999 INCREMENT BY 1 NOCACHE CYCLE;

CREATE TABLE OBJTYPE
(
  OBJECT_TYPE_ID NUMBER(20)   NOT NULL ENABLE,
  PARENT_ID      NUMBER(20),
  CODE           VARCHAR2(20) NOT NULL UNIQUE,
  NAME           VARCHAR2(200 BYTE),
  DESCRIPTION    VARCHAR2(1000 BYTE),
  CONSTRAINT CON_OBJECT_TYPE_ID PRIMARY KEY (OBJECT_TYPE_ID),
  CONSTRAINT CON_PARENT_ID FOREIGN KEY (PARENT_ID) REFERENCES OBJTYPE (OBJECT_TYPE_ID) ON DELETE CASCADE ENABLE
);

CREATE TABLE ATTRTYPE (
  ATTR_ID            NUMBER(20) NOT NULL,
  OBJECT_TYPE_ID     NUMBER(20) NOT NULL,
  OBJECT_TYPE_ID_REF NUMBER(20),
  CODE               VARCHAR2(20),
  NAME               VARCHAR2(200 BYTE),
  CONSTRAINT CON_ATTR_ID PRIMARY KEY (ATTR_ID),
  CONSTRAINT CON_ATTR_OBJECT_TYPE_ID FOREIGN KEY (OBJECT_TYPE_ID) REFERENCES OBJTYPE (OBJECT_TYPE_ID),
  CONSTRAINT CON_ATTR_OBJECT_TYPE_ID_REF FOREIGN KEY (OBJECT_TYPE_ID_REF) REFERENCES OBJTYPE (OBJECT_TYPE_ID)
);

CREATE TABLE OBJECTS (
  OBJECT_ID      NUMBER(20) NOT NULL,
  PARENT_ID      NUMBER(20),
  OBJECT_TYPE_ID NUMBER(20) NOT NULL,
  NAME           VARCHAR2(2000 BYTE),
  DESCRIPTION    VARCHAR2(4000 BYTE),
  CONSTRAINT CON_OBJECTS_ID PRIMARY KEY (OBJECT_ID),
  CONSTRAINT CON_PARENTS_ID FOREIGN KEY (PARENT_ID) REFERENCES OBJECTS (OBJECT_ID) ON DELETE CASCADE DEFERRABLE,
  CONSTRAINT CON_OBJ_TYPE_ID FOREIGN KEY (OBJECT_TYPE_ID) REFERENCES OBJTYPE (OBJECT_TYPE_ID)
);

CREATE TABLE ATTRIBUTES
(
  ATTR_ID    NUMBER(20) NOT NULL,
  OBJECT_ID  NUMBER(20) NOT NULL,
  VALUE      VARCHAR2(4000 BYTE),
  DATE_VALUE DATE,
  CONSTRAINT CON_ATTRIBUTES_PK PRIMARY KEY (ATTR_ID, OBJECT_ID),
  CONSTRAINT CON_AOBJECT_ID FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS (OBJECT_ID) ON DELETE CASCADE,
  CONSTRAINT CON_AATTR_ID FOREIGN KEY (ATTR_ID) REFERENCES ATTRTYPE (ATTR_ID) ON DELETE CASCADE
);

CREATE TABLE OBJREFERENCE
(
  ATTR_ID   NUMBER(20) NOT NULL,
  REFERENCE NUMBER(20) NOT NULL,
  OBJECT_ID NUMBER(20) NOT NULL,
  CONSTRAINT CON_OBJREFERENCE_PK PRIMARY KEY (ATTR_ID, REFERENCE, OBJECT_ID),
  CONSTRAINT CON_REFERENCE FOREIGN KEY (REFERENCE) REFERENCES OBJECTS (OBJECT_ID) ON DELETE CASCADE,
  CONSTRAINT CON_ROBJECT_ID FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS (OBJECT_ID) ON DELETE CASCADE,
  CONSTRAINT CON_RATTR_ID FOREIGN KEY (ATTR_ID) REFERENCES ATTRTYPE (ATTR_ID) ON DELETE CASCADE
);

INSERT INTO OBJTYPE(OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION)
    VALUES (1, NULL, 'MOVIE', NULL, NULL);

INSERT INTO OBJTYPE(OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION)
    VALUES (2, NULL, 'HALL', NULL, NULL);

INSERT INTO OBJTYPE(OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION)
    VALUES (3, NULL, 'ZONE', NULL, NULL);

INSERT INTO OBJTYPE(OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION)
    VALUES (4, NULL, 'PLACE', NULL, NULL);

INSERT INTO OBJTYPE(OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION)
    VALUES (5, NULL, 'SEANCE', NULL, NULL);

INSERT INTO OBJTYPE(OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION)
    VALUES (6, NULL, 'TICKET', NULL, NULL);

INSERT INTO OBJTYPE(OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION)
    VALUES (7, NULL, 'PRICE', NULL, NULL);

INSERT INTO ATTRTYPE(ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME)
    VALUES (1, 1, NULL, 'DESCRIPTION', NULL);

INSERT INTO ATTRTYPE(ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME)
    VALUES (2, 1, NULL, 'DURATION', NULL);

INSERT INTO ATTRTYPE(ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME)
    VALUES (3, 1, NULL, 'IMDB', NULL);

INSERT INTO ATTRTYPE(ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME)
    VALUES (4, 1, NULL, 'PERIODICITY', NULL);

INSERT INTO ATTRTYPE(ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME)
    VALUES (5, 1, NULL, 'BASE_PRICE', NULL);

INSERT INTO ATTRTYPE(ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME)
    VALUES (6, 1, NULL, 'ROLLING_START', NULL);

INSERT INTO ATTRTYPE(ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME)
    VALUES (7, 1, NULL, 'ROLLING_END', NULL);

INSERT INTO ATTRTYPE(ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME)
    VALUES (8, 1, NULL, 'POSTER', NULL);

INSERT INTO ATTRTYPE(ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME)
    VALUES (9, 4, NULL, 'NUMBER', NULL);

INSERT INTO ATTRTYPE(ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME)
    VALUES (10, 4, NULL, 'ROW', NULL);

INSERT INTO ATTRTYPE(ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME)
    VALUES (11, 4, 2, 'HALL_REF', NULL);

INSERT INTO ATTRTYPE(ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME)
    VALUES (12, 4, 3, 'ZONE_REF', NULL);