DELETE FROM OBJREFERENCE;
DELETE FROM ATTRIBUTES;
DELETE FROM OBJECTS;
DELETE FROM ATTRTYPE;
DELETE FROM OBJTYPE;

INSERT INTO OBJTYPE(OBJECT_TYPE_ID, PARENT_ID, CODE, NAME, DESCRIPTION)
VALUES (1, NULL, 'DUMMY', 'dummy', 'test object');

INSERT INTO ATTRTYPE(ATTR_ID, OBJECT_TYPE_ID, OBJECT_TYPE_ID_REF, CODE, NAME)
VALUES (1, 1, NULL, 'NAME', 'name');