INSERT ALL
INTO OBJECTS(OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION)
VALUES (get_obj_id.nextval, NULL, 1, 'Ghost in the Shell', NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (1, get_obj_id.currval, 'A cyborg policewoman attempts to bring down a nefarious computer hacker.', NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (2, get_obj_id.currval, 86, NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (3, get_obj_id.currval, 90, NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (4, get_obj_id.currval, 6, NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (5, get_obj_id.currval, 93, NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (6, get_obj_id.currval, NULL, DATE '2016-11-15')
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (7, get_obj_id.currval, NULL, DATE '2017-02-15')
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (8, get_obj_id.currval, 'https://images-na.ssl-images-amazon.com/images/M/MV5BNzQ0NDcwMDA4Ml5BMl5BanBnXkFtZTgwNDg4OTg1MDI@._V1_SY1000_SX675_AL_.jpg', NULL)
SELECT * FROM DUAL;


INSERT ALL
INTO OBJECTS(OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION)
VALUES (get_obj_id.nextval, NULL, 1, 'Beauty and the Beast', NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (1, get_obj_id.currval, 'An adaptation of the classic fairy-tale about a monstrous prince and a young woman who fall in love.', NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (2, get_obj_id.currval, 110, NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (3, get_obj_id.currval, 70, NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (4, get_obj_id.currval, 5, NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (5, get_obj_id.currval, 148, NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (6, get_obj_id.currval, NULL, DATE '2016-10-01')
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (7, get_obj_id.currval, NULL, DATE '2017-01-27')
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (8, get_obj_id.currval, 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjEyMzExMDczNV5BMl5BanBnXkFtZTgwMzYzMjczOTE@._V1_SY1000_CR0,0,674,1000_AL_.jpg', NULL)
SELECT * FROM DUAL;


INSERT ALL
INTO OBJECTS(OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION)
VALUES (get_obj_id.nextval, NULL, 1, 'Fantastic Beasts and Where to Find Them', NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (1, get_obj_id.currval, 'The adventures of writer Newt Scamander in New York''s secret community of witches and wizards seventy years before Harry Potter reads his book in school.', NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (2, get_obj_id.currval, 164, NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (3, get_obj_id.currval, 90, NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (4, get_obj_id.currval, 6, NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (5, get_obj_id.currval, 123, NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (6, get_obj_id.currval, NULL, DATE '2016-12-20')
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (7, get_obj_id.currval, NULL, DATE '2017-03-07')
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (8, get_obj_id.currval, 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjMxOTM1OTI4MV5BMl5BanBnXkFtZTgwODE5OTYxMDI@._V1_SY1000_CR0,0,674,1000_AL_.jpg', NULL)
SELECT * FROM DUAL;


INSERT ALL
INTO OBJECTS(OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION)
VALUES (get_obj_id.nextval, NULL, 1, 'Manchester by the Sea', NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (1, get_obj_id.currval, 'An uncle is forced to take care of his teenage nephew after the boy''s father dies.', NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (2, get_obj_id.currval, 186, NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (3, get_obj_id.currval, 80, NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (4, get_obj_id.currval, 3, NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (5, get_obj_id.currval, 54, NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (6, get_obj_id.currval, NULL, DATE '2016-08-06')
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (7, get_obj_id.currval, NULL, DATE '2016-12-03')
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (8, get_obj_id.currval, 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTYxMjk0NDg4Ml5BMl5BanBnXkFtZTgwODcyNjA5OTE@._V1_SY1000_CR0,0,674,1000_AL_.jpg', NULL)
SELECT * FROM DUAL;

INSERT ALL
INTO OBJECTS(OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION)
VALUES (get_obj_id.nextval, NULL, 5, 'Seance 1', NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (13, get_obj_id.currval, NULL, TO_DATE('2016-12-30 13:00','YYYY-MM-DD HH24:MI'))
INTO OBJREFERENCE(ATTR_ID, REFERENCE, OBJECT_ID)
VALUES (14, get_obj_id.currval, 219)
INTO OBJREFERENCE(ATTR_ID, REFERENCE, OBJECT_ID)
VALUES (15, get_obj_id.currval, 1)
SELECT * FROM dual;

INSERT ALL
INTO OBJECTS(OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION)
VALUES (get_obj_id.nextval, NULL, 5, 'Seance 2', NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (13, get_obj_id.currval, NULL, TO_DATE('2016-12-30 16:00','YYYY-MM-DD HH24:MI'))
INTO OBJREFERENCE(ATTR_ID, REFERENCE, OBJECT_ID)
VALUES (14, get_obj_id.currval, 219)
INTO OBJREFERENCE(ATTR_ID, REFERENCE, OBJECT_ID)
VALUES (15, get_obj_id.currval, 2)
SELECT * FROM dual;

INSERT ALL
INTO OBJECTS(OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION)
VALUES (get_obj_id.nextval, NULL, 5, 'Seance 2', NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (13, get_obj_id.currval, NULL, TO_DATE('2016-12-30 16:00','YYYY-MM-DD HH24:MI'))
INTO OBJREFERENCE(ATTR_ID, REFERENCE, OBJECT_ID)
VALUES (14, get_obj_id.currval, 219)
INTO OBJREFERENCE(ATTR_ID, REFERENCE, OBJECT_ID)
VALUES (15, get_obj_id.currval, 2)
SELECT * FROM dual;

INSERT ALL
INTO OBJECTS(OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION)
VALUES (get_obj_id.nextval, NULL, 5, 'Seance 2', NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (13, get_obj_id.currval, NULL, TO_DATE('2016-12-30 16:00','YYYY-MM-DD HH24:MI'))
INTO OBJREFERENCE(ATTR_ID, REFERENCE, OBJECT_ID)
VALUES (14, get_obj_id.currval, 219)
INTO OBJREFERENCE(ATTR_ID, REFERENCE, OBJECT_ID)
VALUES (15, get_obj_id.currval, 2)
SELECT * FROM dual;

INSERT ALL
INTO OBJECTS(OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION)
VALUES (get_obj_id.nextval, NULL, 5, 'Seance 2', NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (13, get_obj_id.currval, NULL, TO_DATE('2016-12-30 16:00','YYYY-MM-DD HH24:MI'))
INTO OBJREFERENCE(ATTR_ID, REFERENCE, OBJECT_ID)
VALUES (14, get_obj_id.currval, 219)
INTO OBJREFERENCE(ATTR_ID, REFERENCE, OBJECT_ID)
VALUES (15, get_obj_id.currval, 2)
SELECT * FROM dual;

INSERT ALL
INTO OBJECTS(OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION)
VALUES (get_obj_id.nextval, NULL, 5, 'Seance 2', NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (13, get_obj_id.currval, NULL, TO_DATE('2016-12-30 16:00','YYYY-MM-DD HH24:MI'))
INTO OBJREFERENCE(ATTR_ID, REFERENCE, OBJECT_ID)
VALUES (14, get_obj_id.currval, 219)
INTO OBJREFERENCE(ATTR_ID, REFERENCE, OBJECT_ID)
VALUES (15, get_obj_id.currval, 2)
SELECT * FROM dual;

INSERT ALL
INTO OBJECTS(OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION)
VALUES (get_obj_id.nextval, NULL, 7, 'Seance 1 AA', NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (22, get_obj_id.currval, 0, NULL)
INTO OBJREFERENCE(ATTR_ID, REFERENCE, OBJECT_ID)
VALUES (23, get_obj_id.currval, 3)
INTO OBJREFERENCE(ATTR_ID, REFERENCE, OBJECT_ID)
VALUES (24, get_obj_id.currval, 223)
SELECT * FROM dual;

INSERT ALL
INTO OBJECTS(OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION)
VALUES (get_obj_id.nextval, NULL, 7, 'Seance 1 BB', NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (22, get_obj_id.currval, 10, NULL)
INTO OBJREFERENCE(ATTR_ID, REFERENCE, OBJECT_ID)
VALUES (23, get_obj_id.currval, 4)
INTO OBJREFERENCE(ATTR_ID, REFERENCE, OBJECT_ID)
VALUES (24, get_obj_id.currval, 223)
SELECT * FROM dual;

INSERT ALL
INTO OBJECTS(OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION)
VALUES (get_obj_id.nextval, NULL, 7, 'Seance 1 CC', NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (22, get_obj_id.currval, 20, NULL)
INTO OBJREFERENCE(ATTR_ID, REFERENCE, OBJECT_ID)
VALUES (23, get_obj_id.currval, 5)
INTO OBJREFERENCE(ATTR_ID, REFERENCE, OBJECT_ID)
VALUES (24, get_obj_id.currval, 223)
SELECT * FROM dual;

INSERT ALL
INTO OBJECTS(OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION)
VALUES (get_obj_id.nextval, NULL, 7, 'Seance 2 DD', NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (22, get_obj_id.currval, 0, NULL)
INTO OBJREFERENCE(ATTR_ID, REFERENCE, OBJECT_ID)
VALUES (23, get_obj_id.currval, 6)
INTO OBJREFERENCE(ATTR_ID, REFERENCE, OBJECT_ID)
VALUES (24, get_obj_id.currval, 224)
SELECT * FROM dual;

INSERT ALL
INTO OBJECTS(OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION)
VALUES (get_obj_id.nextval, NULL, 7, 'Seance 2 EE', NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (22, get_obj_id.currval, 10, NULL)
INTO OBJREFERENCE(ATTR_ID, REFERENCE, OBJECT_ID)
VALUES (23, get_obj_id.currval, 7)
INTO OBJREFERENCE(ATTR_ID, REFERENCE, OBJECT_ID)
VALUES (24, get_obj_id.currval, 224)
SELECT * FROM dual;

INSERT ALL
INTO OBJECTS(OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION)
VALUES (get_obj_id.nextval, NULL, 7, 'Seance 2 HH', NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (22, get_obj_id.currval, 20, NULL)
INTO OBJREFERENCE(ATTR_ID, REFERENCE, OBJECT_ID)
VALUES (23, get_obj_id.currval, 8)
INTO OBJREFERENCE(ATTR_ID, REFERENCE, OBJECT_ID)
VALUES (24, get_obj_id.currval, 224)
SELECT * FROM dual;

INSERT ALL
INTO OBJECTS(OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION)
VALUES (get_obj_id.nextval, NULL, 6, 'Ticket 1', NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (16, get_obj_id.currval, 2044, NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (17, get_obj_id.currval, 'random@ex.com', NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (18, get_obj_id.currval, 100, NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (19, get_obj_id.currval, 'FALSE', NULL)
INTO OBJREFERENCE(ATTR_ID, REFERENCE, OBJECT_ID)
VALUES (20, get_obj_id.currval, 223)
INTO OBJREFERENCE(ATTR_ID, REFERENCE, OBJECT_ID)
VALUES (21, get_obj_id.currval, 9)
SELECT * FROM dual;

INSERT ALL
INTO OBJECTS(OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION)
VALUES (get_obj_id.nextval, NULL, 6, 'Ticket 2', NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (16, get_obj_id.currval, 1488, NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (17, get_obj_id.currval, 'example@gmail.com', NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (18, get_obj_id.currval, 110, NULL)
INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
VALUES (19, get_obj_id.currval, 'TRUE', NULL)
INTO OBJREFERENCE(ATTR_ID, REFERENCE, OBJECT_ID)
VALUES (20, get_obj_id.currval, 223)
INTO OBJREFERENCE(ATTR_ID, REFERENCE, OBJECT_ID)
VALUES (21, get_obj_id.currval, 47)
SELECT * FROM dual;
  
  