package com.netcracker.cinema.web.adminModifyMovie;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MovieFormDesign extends FormLayout {
	protected TextField image;
	protected TextField movie;
	protected TextField duration;
	protected TextField imdb;
	protected TextField basePrice;
	protected TextField periodicity;
	protected TextField timeOut;
	protected DateField rollingStart;
	protected DateField rollingEnd;
	protected TextArea description;
	protected Button save;
	protected Button delete;

	public MovieFormDesign() {
		Design.read(this);
	}
}
