INSERT INTO OBJECTS(OBJECT_ID, PARENT_ID, OBJECT_TYPE_ID, NAME, DESCRIPTION)
    VALUES (1000, NULL, 1, 'Ghost in the Shell', NULL);

INSERT INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
    VALUES (1, 1000, 'A cyborg policewoman attempts to bring down a nefarious computer hacker.', NULL);

INSERT INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
    VALUES (2, 1000, 86, NULL);

INSERT INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
    VALUES (3, 1000, 90, NULL);

INSERT INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
    VALUES (4, 1000, 6, NULL);

INSERT INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
    VALUES (5, 1000, 100, NULL);

INSERT INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
    VALUES (6, 1000, NULL, DATE '2016-11-15');

INSERT INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
    VALUES (7, 1000, NULL, DATE '2017-02-15');

INSERT INTO ATTRIBUTES(ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE)
    VALUES (8, 1000, 'https://images-na.ssl-images-amazon.com/images/M/MV5BNzQ0NDcwMDA4Ml5BMl5BanBnXkFtZTgwNDg4OTg1MDI@._V1_SY1000_SX675_AL_.jpg', NULL);